enum ActionTypes {
  LOAD_ATHLETE_SUGGESTIONS = 'app/AdminResults/LOAD_ATHLETE_SUGGESTIONS',
  SET_ATHLETE_SUGGESTIONS = 'app/AdminResults/SET_ATHLETE_SUGGESTIONS',
  SET_ATHLETE_FILTER_SELECTED_VALUE = 'app/AdminResults/SET_ATHLETE_FILTER_SELECTED_VALUE',
  CHANGE_ATHLETE_FILTER_ORDER = 'app/AdminResults/CHANGE_ATHLETE_FILTER_ORDER',
  CHANGE_ATHLETE_FILTER_POINTS = 'app/AdminResults/CHANGE_ATHLETE_FILTER_POINTS',
  LOAD_CONTEST_SUGGESTIONS = 'app/AdminResults/LOAD_CONTEST_SUGGESTIONS',
  SET_CONTEST_SUGGESTIONS = 'app/AdminResults/SET_CONTEST_SUGGESTIONS',
  SET_CONTEST_FILTER_SELECTED_VALUE = 'app/AdminResults/SET_CONTEST_FILTER_SELECTED_VALUE',
  LOAD_RESULTS = 'app/AdminResults/LOAD_RESULTS',
  SET_RESULTS = 'app/AdminResults/SET_RESULTS',
  CLEAR_FORM = 'app/AdminResults/CLEAR_FORM',
  ADD_ATHLETE_FILTER = 'app/AdminResults/ADD_ATHLETE_FILTER',
}

export default ActionTypes;
