enum ActionTypes {
  LOAD_SUGGESTIONS = 'app/Athlete/LOAD_SUGGESTIONS',
  SUGGESTIONS_LOADED = 'app/Athlete/SUGGESTIONS_LOADED',
  SELECT_SUGGESTION = 'app/Athlete/SELECT_SUGGESTION',
  CLEAR_SUGGESTIONS = 'app/Athlete/CLEAR_SUGGESTIONS',
  CHANGE_SELECTED_FILTERS = 'app/Athlete/CHANGE_SELECTED_FILTERS',
  SELECT_TABLE_ROW = 'app/Athlete/SELECT_TABLE_ROW',
  LOAD_TABLE_ITEMS = 'app/Athlete/LOAD_TABLE_ITEMS',
  SET_TABLE_ITEMS = 'app/Athlete/SET_TABLE_ITEMS',
  SET_ATHLETE = 'app/Athlete/SET_ATHLETE',
}

export default ActionTypes;
