enum ActionTypes {
  LOAD_ATHLETE_SUGGESTIONS = 'app/AdminAthlete/LOAD_ATHLETE_SUGGESTIONS',
  SET_ATHLETE_SUGGESTIONS = 'app/AdminAthlete/SET_ATHLETE_SUGGESTIONS',
  SET_ATHLETE_FILTER_SELECTED_VALUE = 'app/AdminAthlete/SET_ATHLETE_FILTER_SELECTED_VALUE',
  LOAD_ATHLETE = 'app/AdminAthlete/LOAD_ATHLETE',
  SET_ATHLETE = 'app/AdminAthlete/SET_ATHLETE',
}

export default ActionTypes;
