enum ActionTypes {
  LOAD_TABLE_ITEMS = 'app/Rankings/LOAD_TABLE_ITEMS',
  ADD_TABLE_ITEMS = 'app/Rankings/ADD_TABLE_ITEMS',
  LOAD_NEXT_TABLE_ITEMS = 'app/Rankings/LOAD_NEXT_TABLE_ITEMS',
  LOAD_CATEGORIES = 'app/Rankings/LOAD_CATEGORIES',
  SET_CATEGORIES = 'app/Rankings/SET_CATEGORIES',
  SET_CATEGORY_SELECTED_VALUE = 'app/Rankings/SET_CATEGORY_SELECTED_VALUE',
  LOAD_ATHLETE_SUGGESTIONS = 'app/Rankings/LOAD_ATHLETE_SUGGESTIONS',
  LOAD_COUNTRY_SUGGESTIONS = 'app/Rankings/LOAD_COUNTRY_SUGGESTIONS',
  SET_COUNTRY_SUGGESTIONS = 'app/Rankings/SET_COUNTRY_SUGGESTIONS',
  SET_ATHLETE_SUGGESTIONS = 'app/Rankings/SET_ATHLETE_SUGGESTIONS',
  SET_ATHLETE_FILTER_SELECTED_VALUE = 'app/Rankings/SET_ATHLETE_FILTER_SELECTED_VALUE',
  SET_COUNTRY_FILTER_SELECTED_VALUE = 'app/Rankings/SET_COUNTRY_FILTER_SELECTED_VALUE',
}

export default ActionTypes;
