enum ActionTypes {
  LOAD_SUGGESTIONS = 'app/Contest/LOAD_SUGGESTIONS',
  SUGGESTIONS_LOADED = 'app/Contest/SUGGESTIONS_LOADED',
  SELECT_SUGGESTION = 'app/Contest/SELECT_SUGGESTION',
  CLEAR_SUGGESTIONS = 'app/Contest/CLEAR_SUGGESTIONS',
  CHANGE_SELECTED_FILTERS = 'app/Contest/CHANGE_SELECTED_FILTERS',
  SELECT_TABLE_ROW = 'app/Contest/SELECT_TABLE_ROW',
  LOAD_TABLE_ITEMS = 'app/Contest/LOAD_TABLE_ITEMS',
  SET_TABLE_ITEMS = 'app/Contest/SET_TABLE_ITEMS',
  SET_CONTEST = 'app/Contest/SET_CONTEST',
}

export default ActionTypes;
