enum ActionTypes {
  LOAD_CONTEST_SUGGESTIONS = 'app/AdminContest/LOAD_CONTEST_SUGGESTIONS',
  SET_CONTEST_SUGGESTIONS = 'app/AdminContest/SET_CONTEST_SUGGESTIONS',
  SET_CONTEST_FILTER_SELECTED_VALUE = 'app/AdminContest/SET_CONTEST_FILTER_SELECTED_VALUE',
  LOAD_CONTEST = 'app/AdminContest/LOAD_CONTEST',
  SET_CONTEST = 'app/AdminContest/SET_CONTEST',
  LOAD_COUNTRY_SUGGESTIONS = 'app/AdminContest/LOAD_COUNTRY_SUGGESTIONS',
  SET_COUNTRY_SUGGESTIONS = 'app/AdminContest/SET_COUNTRY_SUGGESTIONS',
  CLEAR_FORM = 'app/AdminContest/CLEAR_FORM',
  LOAD_DISCIPLINES = 'app/AdminContest/LOAD_DISCIPLINES',
  SET_DISCIPLINES = 'app/AdminContest/SET_DISCIPLINES',
  LOAD_CATEGORIES = 'app/AdminContest/LOAD_CATEGORIES',
  SET_CATEGORIES = 'app/AdminContest/SET_CATEGORIES',
  LOAD_GENDERS = 'app/AdminContest/LOAD_GENDERS',
  SET_GENDERS = 'app/AdminContest/SET_GENDERS',
}

export default ActionTypes;
