enum ActionTypes {
  LOAD_SUGGESTIONS = 'app/Contests/LOAD_SUGGESTIONS',
  SUGGESTIONS_LOADED = 'app/Contests/SUGGESTIONS_LOADED',
  SELECT_SUGGESTION = 'app/Contests/SELECT_SUGGESTION',
  CLEAR_SUGGESTIONS = 'app/Contests/CLEAR_SUGGESTIONS',
  CHANGE_SELECTED_FILTERS = 'app/Contests/CHANGE_SELECTED_FILTERS',
  SELECT_TABLE_ROW = 'app/Contests/SELECT_TABLE_ROW',
  LOAD_TABLE_ITEMS = 'app/Contests/LOAD_TABLE_ITEMS',
  SET_TABLE_ITEMS = 'app/Contests/SET_TABLE_ITEMS',
}

export default ActionTypes;
