enum ActionTypes {
  LOAD_TABLE_ITEMS = 'app/Contests/LOAD_TABLE_ITEMS',
  ADD_TABLE_ITEMS = 'app/Contests/ADD_TABLE_ITEMS',
  LOAD_NEXT_TABLE_ITEMS = 'app/Contests/LOAD_NEXT_TABLE_ITEMS',
  LOAD_CATEGORIES = 'app/Contests/LOAD_CATEGORIES',
  SET_CATEGORIES = 'app/Contests/SET_CATEGORIES',
  SET_CATEGORY_SELECTED_VALUE = 'app/Contests/SET_CATEGORY_SELECTED_VALUE',
  LOAD_CONTEST_SUGGESTIONS = 'app/Contests/LOAD_CONTEST_SUGGESTIONS',
  SET_CONTEST_SUGGESTIONS = 'app/Contests/SET_CONTEST_SUGGESTIONS',
  SET_CONTEST_FILTER_SELECTED_VALUE = 'app/Contests/SET_CONTESTFILTER_SELECTED_VALUE',
  // SET_CATEGORIES_STATUS = 'app/Contests/SET_CATEGORIES_STATUS',
}

export default ActionTypes;
